#!/usr/bin/env bash

#SBATCH -o /homes/5/fd881/slurm_log/med-image-drift-scoring_er_wohardclasses-%j.out
#SBATCH -J med-image-drift-scoring
#SBATCH -p pubgpu,rtx8000
#SBATCH -A qtim
#SBATCH -n 1
#SBATCH --cpus-per-task=12
#SBATCH --gpus 1
#SBATCH --mem 128G
#SBATCH -t 18:00:00

export PYENV_VERSION="med-image-drift"
export PYTHONPATH="${HOME}/repos/MedImaging-ModelDriftMonitoring/src":${PYTHONPATH}

python ${HOME}/repos/MedImaging-ModelDriftMonitoring/src/scripts/finetune/score.py \
    --frontal_only 1 \
    --batch_size 16 \
    --data_folder /autofs/cluster/qtim/datasets/private/xray_drift/dicom/ \
    --model '/autofs/cluster/qtim/projects/xray_drift/models/mgb/classification_imagenet_monaitransform_onlyer_wohardclasses/checkpoints/epoch=043.ckpt' \
    --dataset mgb \
    --output_dir /autofs/cluster/qtim/projects/xray_drift/inferences/classification_imagenet_monaitransform_onlyer_wohardclasses \
    --num_workers 12 \
    --cache_folder /vast/qtim/projects/xray-drift/numpy_cache/ \