#!/usr/bin/env bash

#SBATCH -o /homes/8/cpb28/slurm_log/med-image-drift-scoring-%j.out
#SBATCH -J med-image-drift-scoring
#SBATCH -p rtx6000,rtx8000
#SBATCH -A qtim
#SBATCH -n 1
#SBATCH --cpus-per-task=1
#SBATCH --gpus 1
#SBATCH --mem 8G
#SBATCH -t 12:00:00

export PYENV_VERSION="med-image-drift"
export PYTHONPATH="${HOME}/repos/MedImaging-ModelDriftMonitoring/src":${PYTHONPATH}

python ${HOME}/repos/MedImaging-ModelDriftMonitoring/src/scripts/finetune/score.py \
    --data_folder /autofs/cluster/qtim/datasets/private/xray_drift/dicom/ \
    --cache_folder /autofs/cluster/qtim/projects/xray_drift/numpy_cache/ \
    --model '/autofs/cluster/qtim/projects/xray_drift/models/mgb/from_chexpert_retrain_frontal_only_lr1e-4/checkpoints/epoch=000.ckpt' \
    --dataset mgb \
    --output_dir /autofs/cluster/qtim/projects/xray_drift/inferences/mgb_data_from_chexpert_retrain_frontal_only_lr1e-4 \
    --num_workers 0
