freeze_backbone: 0
gamma: 0.1
labels:
- Atelectasis
- Consolidation
- Edema
- Lung Lesion
- Lung Opacity
- Pleural Effusion
- Pneumonia
- Pneumothorax
learning_rate: 0.001
map_location: null
num_classes: 8
params:
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  batch_size: 64
  benchmark: false
  cache_folder: !!python/object/apply:pathlib.PosixPath
  - /
  - autofs
  - cluster
  - qtim
  - projects
  - xray_drift
  - numpy_cache
  channels: 3
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  csv_folder: !!python/object/apply:pathlib.PosixPath
  - /
  - autofs
  - cluster
  - qtim
  - datasets
  - private
  - xray_drift
  - csv
  data_folder: /autofs/cluster/qtim/datasets/private/xray_drift/dicom/
  default_root_dir: null
  deterministic: false
  devices: null
  distributed_backend: null
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  freeze_backbone: 0
  frontal_only: 1
  gamma: 0.1
  gpus: 1
  gradient_clip_algorithm: norm
  gradient_clip_val: 0.0
  image_size: 320
  ipus: null
  labels_csv: !!python/object/apply:pathlib.PosixPath
  - /
  - autofs
  - cluster
  - qtim
  - projects
  - xray_drift
  - preprocessed_labels
  - labels.csv
  learning_rate: 0.001
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  max_epochs: null
  max_steps: null
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  normalize: imagenet
  num_classes: 8
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 2
  num_workers: 12
  output_dir: /autofs/cluster/qtim/projects/xray_drift/models/mgb/from_chexpert_retrain_frontal_only_felix
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  pretrained: /autofs/cluster/qtim/projects/xray_drift/models/epoch=4-step=29844.ckpt
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  run_azure: 0
  step_size: 7
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  test_frontal_only: null
  tpu_cores: null
  track_grad_norm: -1
  train_frontal_only: null
  truncated_bptt_steps: null
  val_check_interval: 1.0
  val_frontal_only: null
  weight_decay: 1.0e-05
  weights_save_path: null
  weights_summary: top
pretrained: /autofs/cluster/qtim/projects/xray_drift/models/epoch=4-step=29844.ckpt
step_size: 7
